server:
  port: 8084

spring:
  application:
    name: github-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andrey528/ClothingStoreSpringProject.git
          basedir: file:///tmp/ClothingStore
          default-label: main