server:
  port: 8084

spring:
  application:
    name: github-config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:Andrey528/ClothingStoreSpringProjectConfigs.git
          basedir: file:///tmp/ClothingStore
          default-label: main