server:
  port: 8082

spring:
  application:
    name: payment-server

  datasource:
    url: jdbc:mysql://localhost:3306/walletDb?createDatabaseIfNotExist=TRUE
    username: "root"
    password: "0d5u8n8g"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: eclient

  config:
    import: configserver:http://localhost:8084