server:
  port: 8083

spring:
  application:
    name: api-gateway
  profiles:
    active: eurekaclient

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  config:
    import: configserver:http://localhost:8084