server:
  port: 8083

spring:
  application:
    name: api-gateway

routes:
  - id: resource-server
    uri: http://localhost:8081/
    predicates:
      - Path=/product/**
  - id: payment-server
    uri: http://localhost:8082/
    predicates:
      - Path=/**